services:
  - type: web
    name: srag-dashboard
    runtime: docker
    dockerContext: .
    dockerfilePath: ./frontend.Dockerfile
    healthCheckPath: /

  - type: pserv
    name: backend
    runtime: docker
    dockerContext: .
    dockerfilePath: ./backend.Dockerfile
