import { useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { api } from '../services/api';

export function useCitizenData(
  active: boolean,
  profile: string[],
  raceFilter: string[],
  genderFilter: string[],
  zoneFilter?: string[],
  bairroFilter?: string[],
  unitFilter?: string[],
  years?: number[],
  agents?: string[],
  maternalFilter?: string[],
  occupationFilter?: string[],
  schooling?: string[],
  riskFactors?: string[],
  months?: number[],
  days?: number[],
) {
  const [swimmerVirus, setSwimmerVirus] = useState<'covid' | 'gripe'>('covid');

  const queryKey = [
    'citizenData',
    profile,
    raceFilter,
    genderFilter,
    zoneFilter,
    bairroFilter,
    unitFilter,
    years,
    agents,
    maternalFilter,
    occupationFilter,
    schooling,
    riskFactors,
    months,
    days,
    swimmerVirus,
  ];

  const { data, isLoading } = useQuery({
    queryKey,
    queryFn: async () => {
      const [bootstrap, vaccine, survivalData, timeline] = await Promise.all([
        api.fetchCitizenBootstrap(
          profile,
          raceFilter,
          genderFilter,
          zoneFilter,
          bairroFilter,
          unitFilter,
          years,
          agents,
          maternalFilter,
          occupationFilter,
          schooling,
          riskFactors,
          months,
          days,
        ),
        api.fetchVaccinationProfile(
          profile,
          raceFilter,
          genderFilter,
          zoneFilter,
          bairroFilter,
          unitFilter,
          years,
          agents,
          maternalFilter,
          occupationFilter,
          schooling,
          riskFactors,
          months,
          days,
        ),
        api.fetchVaccineSurvival(
          profile,
          raceFilter,
          genderFilter,
          zoneFilter,
          bairroFilter,
          unitFilter,
          years,
          agents,
          maternalFilter,
          occupationFilter,
          schooling,
          riskFactors,
          months,
          days,
        ),
        api.fetchTimelineAgg(
          swimmerVirus,
          profile,
          raceFilter,
          genderFilter,
          zoneFilter,
          bairroFilter,
          unitFilter,
          years,
          agents,
          maternalFilter,
          occupationFilter,
          schooling,
          riskFactors,
          months,
          days,
        ),
      ]);

      return { bootstrap, vaccine, survivalData, timeline };
    },
    enabled: active,
    staleTime: 5 * 60 * 1000,
  });

  return {
    profiles: data?.bootstrap.citizen_profiles?.macro_profiles || [],
    pyramid: data?.bootstrap.citizen_pyramid || [],
    raceProfile: data?.bootstrap.race_profile || [],
    schooling: data?.bootstrap.schooling_profile || [],
    occupation: data?.bootstrap.occupation_profile || [],
    animalContact: data?.bootstrap.animal_contact || [],
    traditionalCommunities: data?.bootstrap.traditional_communities || [],
    symptomsSignature: data?.bootstrap.symptoms_signature || null,
    riskFactors: data?.bootstrap.risk_factors_full || [],
    maternalProfile: data?.bootstrap.maternal_profile || null,
    vaccination: data?.vaccine || null,
    survival: data?.survivalData || null,
    timelineData: data?.timeline || [],
    swimmerVirus,
    setSwimmerVirus,
    loading: isLoading && active,
  };
}
